import createMiddleware from "next-intl/middleware"
import { locales, defaultLocale } from "@/i18n/config"
import { NextResponse } from "next/server"
import type { NextRequest } from "next/server"

/**
 * Combined middleware:
 *  1. Region detection via GeoIP (CF-IPCountry → Accept-Language → default)
 *  2. Locale detection & i18n routing (via next-intl)
 *  3. Block /test/* routes in production
 *  4. Add security response headers (HSTS, X-Frame-Options, etc.)
 *  5. Fix localhost redirect URLs (HOSTNAME=127.0.0.1 in standalone mode)
 *
 * Region detection flow (always re-detects from IP):
 *   1. Use Cloudflare's CF-IPCountry header (most accurate, always fresh)
 *   2. Fall back to Accept-Language header (weak signal for zh-*)
 *   3. Default to "overseas"
 *
 * The detected region is set as a cookie and injected as x-omni-region header,
 * so server components and API routes can read it without client detection.
 *
 * IMPORTANT: In standalone mode with HOSTNAME=127.0.0.1, Next.js middleware
 * generates redirect URLs like http://127.0.0.1:3000/path instead of
 * https://khanfate.com/path. The fixLocalhostRedirects helper patches all
 * redirect Location headers to use the correct external hostname.
 */

const DOMESTIC_COUNTRY_CODES = new Set(["CN", "HK", "MO", "TW"])

type Region = "domestic" | "overseas"

/**
 * Fix localhost redirect URLs generated by Next.js middleware.
 *
 * When HOSTNAME=127.0.0.1 (standalone mode behind nginx), Next.js generates
 * redirect Location headers like http://127.0.0.1:3000/zh/path instead of
 * https://khanfate.com/zh/path. This causes browsers to navigate to localhost
 * which is unreachable from outside the server.
 *
 * This helper rewrites any localhost redirects to use the correct external
 * hostname derived from the request's Host header.
 */
function fixLocalhostRedirects(response: NextResponse, request: NextRequest): NextResponse {
  const location = response.headers.get("location")
  if (!location) return response

  // Only fix localhost/127.0.0.1 redirects
  if (!location.includes("127.0.0.1") && !location.includes("localhost")) return response

  // Derive the correct external URL from the Host header
  const host = request.headers.get("host") || "khanfate.com"
  const proto = request.headers.get("x-forwarded-proto") || "https"

  // Hostname allowlist to prevent open redirect attacks
  const ALLOWED_HOSTS = ["khanfate.com", "www.khanfate.com", "localhost:3000", "127.0.0.1:3000"]
  const safeHost = ALLOWED_HOSTS.includes(host) ? host : "khanfate.com"

  // Extract just the path (and query) from the redirect URL
  try {
    const locUrl = new URL(location)
    const fixedUrl = `${proto}://${safeHost}${locUrl.pathname}${locUrl.search}`
    response.headers.set("location", fixedUrl)
  } catch {
    // If URL parsing fails, try a simple regex replace
    const fixed = location.replace(/https?:\/\/(127\.0\.0\.1|localhost)(:\d+)?/, `${proto}://${safeHost}`)
    response.headers.set("location", fixed)
  }

  return response
}

const intlMiddleware = createMiddleware({
  locales,
  defaultLocale,
  localePrefix: "always",
})

/**
 * Detect user's region from request headers.
 * ALWAYS re-detects from CF-IPCountry on every request.
 * This ensures VPN/proxy IP changes are immediately reflected.
 *
 * Priority: CF-IPCountry (authoritative) > default to overseas
 *
 * IMPORTANT: Accept-Language is NOT used for region detection because it's
 * unreliable — overseas Chinese users often have "zh" in their Accept-Language
 * but should see overseas pricing. When CF-IPCountry is missing (e.g. non-Cloudflare
 * setup), we default to "overseas" which is safer for international users.
 * The client-side API verification provides an additional fallback.
 */
function detectRegion(request: NextRequest): Region {
  // 1. Cloudflare IP country code (most accurate, always fresh)
  const cfCountry = request.headers.get("cf-ipcountry")?.toUpperCase()
  if (cfCountry) {
    // CF-IPCountry is present — trust it as authoritative
    return DOMESTIC_COUNTRY_CODES.has(cfCountry) ? "domestic" : "overseas"
  }

  // 2. Default to overseas (safer for international users)
  // Client-side API verification will correct if needed
  return "overseas"
}

/** Apply common security + cache-control headers to a response */
function applySecurityHeaders(response: NextResponse) {
  // CSP is handled by nginx — do NOT set it here to avoid double-header conflicts
  response.headers.set("X-Content-Type-Options", "nosniff")
  response.headers.set("X-Frame-Options", "DENY")
  response.headers.set("Referrer-Policy", "strict-origin-when-cross-origin")
  response.headers.set("Permissions-Policy", "camera=(), microphone=(), geolocation=()")

  if (process.env.NODE_ENV === "production") {
    response.headers.set(
      "Strict-Transport-Security",
      "max-age=63072000; includeSubDomains; preload",
    )
  }

  // NOTE: Cache-Control is set per-route in next.config.js `headers()` —
  // DO NOT set it here unconditionally, as it would override CDN-friendly
  // cache rules for static assets, SEO pages, and public resources.
}

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl

  // Block test routes in production
  if (process.env.NODE_ENV === "production" && pathname.startsWith("/test")) {
    return new NextResponse("Page Not Found", { status: 404 })
  }

  // SEO SILO redirects (301) — old /seo/* paths to new root-level paths
  const seoRedirects: Record<string, string> = {
    "/seo/bazi": "/bazi",
    "/seo/astrology": "/astrology",
    "/seo/tarot": "/tarot",
    "/seo/face-reading": "/face-reading",
    "/seo/five-elements": "/five-elements",
    "/seo/ziwei": "/ziwei",
    "/seo/palm-reading": "/palm-reading",
    "/seo/zodiac-compatibility": "/astrology/zodiac-compatibility",
  }
  // Match with or without locale prefix (e.g. /en/seo/bazi or /seo/bazi)
  for (const [oldPath, newPath] of Object.entries(seoRedirects)) {
    if (pathname === oldPath || pathname.endsWith(oldPath)) {
      const locale = pathname.match(/^\/(en|zh)/)?.[0] || ""
      const url = request.nextUrl.clone()
      url.pathname = `${locale}${newPath}`
      return NextResponse.redirect(url, 301)
    }
  }

  // Redirect /reading/* to /{locale}/reading/* if locale is missing
  // Skip if path already has a locale prefix (e.g. /en/reading or /zh/reading)
  if (pathname.startsWith("/reading") && !pathname.match(/^\/(en|zh)\//)) {
    const locale = request.cookies.get("NEXT_LOCALE")?.value || "zh"
    const url = request.nextUrl.clone()
    // Redirect /reading (exact) to /readings (list page)
    if (pathname === "/reading") {
      url.pathname = `/${locale}/readings`
    } else {
      url.pathname = `/${locale}${pathname}`
    }
    return fixLocalhostRedirects(NextResponse.redirect(url), request)
  }

  // Run i18n middleware (handles locale detection & redirects)
  const intlResponse = fixLocalhostRedirects(intlMiddleware(request), request)

  // Apply security headers
  applySecurityHeaders(intlResponse)

  // ── Server-side region detection ──
  // Detect region from GeoIP headers and set cookie + header for downstream use
  const region = detectRegion(request)

  // Set region cookie (30-day expiry)
  intlResponse.cookies.set("region", region, {
    maxAge: 30 * 24 * 60 * 60, // 30 days
    path: "/",
    sameSite: "lax",
    httpOnly: true,
    secure: true,
  })

  // Inject region header for server components and API routes
  intlResponse.headers.set("x-omni-region", region)

  return intlResponse
}

export const config = {
  // Run on ALL routes except static assets, API routes, and files with extensions.
  matcher: ["/", "/((?!_next|api|favicon.ico|.*\\.).*)"],
}
